version: '3.4'

services:
  spring-boot-websocket-chat-demo:
    image: spring-boot-websocket-chat-demo
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080
      - 5005:5005