on: [push]

name: visual-testing-cicd

jobs:
  deployMicroservicesDev:
    runs-on: windows-latest
    env:
      TEST_START_PAGE: ghchattybot-dev.k8s.az.jessicadeen.com
    steps:
      # - name: Applitools Build Task
      #   run: |
      #     # set batch ID
      #     APPLITOOLS_BATCH_ID=${{ github.run_id }}

      #     echo "::set-env name=APPLITOOLS_BATCH_ID::${{ github.run_id }}"
          
      #     echo "Setting environment variable APPLITOOLS_BATCH_ID: $APPLITOOLS_BATCH_ID"

      #     # set batch name
      #     APPLITOOLS_BATCH_NAME="GitHub Actions / ${{ github.workflow }}"

      #     echo "::set-env name=APPLITOOLS_BATCH_NAME::GitHub Actions / ${{ github.workflow }}"
          
      #     echo "Setting environment variable APPLITOOLS_BATCH_NAME: $APPLITOOLS_BATCH_NAME"

      #     # set server url
      #     APPLITOOLS_SERVER_URL="https://eyes.applitools.com"

      #     echo "::set-env name=APPLITOOLS_SERVER_URL::https://eyes.applitools.com"
          
      #     echo "Setting environment variable APPLITOOLS_SERVER_URL: $APPLITOOLS_SERVER_URL"

      #     # set batch sequence
      #     APPLITOOLS_BATCH_SEQUENCE="GitHub Actions / ${{ github.workflow }}"

      #     echo "::set-env name=APPLITOOLS_BATCH_SEQUENCE::GitHub Actions / ${{ github.workflow }}"
          
      #     echo "Setting environment variable APPLITOOLS_BATCH_SEQUENCE: $APPLITOOLS_BATCH_SEQUENCE"
      
      # - name: "Setup JDK"
      #   uses: actions/setup-java@v1
      #   with:
      #     java-version: '13'
      - name: git checkout branch
        uses: actions/checkout@v2
        with:
          ref: applitools

      - uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: "Visual Testing"
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}    
        run: mvn -f visual_tests/pom.xml clean test test
